Create bumper.yml
drashland/sockets pull request #74
Opened 2020-08-05 01:44 UTC by ebebbington

Add bumper script. Copied from drash

2020-08-09 16:42 UTC, ebebbington commented
FYI ci is failing on master also

2020-09-13 12:00 UTC, crookse approved these changes

2020-09-13 12:00 UTC, crookse requested changes
need to fix tests

2020-09-13 21:57 UTC, ebebbington commented
closing in favour of a new PR i'll make soon, similar to what the other repos now have (update script)

2020-09-13 21:57 UTC, closed without merging